### ISSUE TITLE
Error with @orion-js/jobs v.1.5.0

### ISSUE THREAD

**Issue by diegoolavarria** [orionjs/orionjs#157]
I got the following error when upgrading @orion-js/jobs from v.1.4.2 to v.1.5.0

> Sentry Logger [Warn]: No DSN provided, backend will not do anything.
> TypeError: (0 , _app.config) is not a function
>     at _default (/home/diego/Projects/recylink/server/node_modules/@orion-js/jobs/lib/job/getExecute.js:25:33)
>     at _default (/home/diego/Projects/recylink/server/node_modules/@orion-js/jobs/lib/job/index.js:47:44)
>     at Object.<anonymous> (/home/xxx/xxx/xxx/server/app/jobs/checkUserRegistration/index.js:4:16)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Module.load (internal/modules/cjs/loader.js:1002:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>     at Module.require (internal/modules/cjs/loader.js:1044:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (/home/xxx/xxx/xxx/server/app/resolvers/Auth/sendEmailVerificationToken.js:3:1)
> Exit code: 1

as you can see, it shows an absolute route when calling a job (I edited the route for privacy)

**Comment by diegoolavarria** [comment]
@jaletelier
